// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PD_FOOD.Infrastructure;

#nullable disable

namespace PD_FOOD.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250402024844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PD_FOOD.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FinancialTransactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1c3f1b2-8f23-4d3e-9e71-f8d0b117f8e2"),
                            Amount = 4800.00m,
                            Date = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Venda de Equipamentos",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("b2f7c3a1-9c44-4201-99a7-84c0f5bdee66"),
                            Amount = 1100.50m,
                            Date = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compra de Materiais",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c8a144b9-1105-4c41-b15c-31dd2e021e97"),
                            Amount = 2200.00m,
                            Date = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Aluguel do Escritório",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("d451f8de-8b99-4fc3-bb62-6b5e23850ad5"),
                            Amount = 3200.00m,
                            Date = new DateTime(2023, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Serviço de Consultoria",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("e3f2f2a1-7d41-4ae3-8e37-c020f0f4b3fc"),
                            Amount = 499.99m,
                            Date = new DateTime(2023, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assinatura de Softwares",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("fdb317aa-66a2-48c3-9d79-8ed1f6224b3d"),
                            Amount = 832.75m,
                            Date = new DateTime(2023, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conta de Energia",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("a6e778c3-09c4-44b7-a693-449ebf160b23"),
                            Amount = 5500.00m,
                            Date = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pagamento de Cliente ABC",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("7b99b6d1-d230-4d7f-94e5-6e8fcb1fd308"),
                            Amount = 650.00m,
                            Date = new DateTime(2023, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reembolso Viagem",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("29a3a1d0-e764-4a6a-b9b2-72d33a3fcbf7"),
                            Amount = 239.90m,
                            Date = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Internet Corporativa",
                            Type = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
